import { createConfig } from "@privy-io/wagmi";
import {
  mainnet,
  optimism,
  cronos,
  bsc,
  gnosis,
  unichain,
  polygon,
  monad,
  sonic,
  worldchain,
  metis,
  soneium,
  mantle,
  base,
  plasma,
  arbitrum,
  celo,
  avalanche,
  ink,
  linea,
  berachain,
  blast,
  scroll,
  hyperEvm,
  megaeth,
} from "wagmi/chains";
import { http, fallback } from "viem";

export const SUPPORTED_CHAINS = [
  mainnet,
  optimism,
  cronos,
  bsc,
  gnosis,
  unichain,
  polygon,
  monad,
  sonic,
  worldchain,
  metis,
  soneium,
  mantle,
  base,
  plasma,
  arbitrum,
  celo,
  avalanche,
  ink,
  linea,
  berachain,
  blast,
  scroll,
  hyperEvm,
  megaeth,
] as const;

// Explicit CORS-friendly public RPC URLs — the wagmi default fallbacks (e.g. eth.merkle.io)
// block requests from browser origins including localhost.
export const wagmiConfig = createConfig({
  chains: SUPPORTED_CHAINS,
  transports: {
    [mainnet.id]:    fallback([
      http("https://rpc.ankr.com/eth"),
      http("https://cloudflare-eth.com"),
      http("https://ethereum-rpc.publicnode.com"),
    ]),
    [optimism.id]:   http("https://mainnet.optimism.io"),
    [cronos.id]:     http("https://evm.cronos.org"),
    [bsc.id]:        http("https://bsc-dataseed.bnbchain.org"),
    [gnosis.id]:     http("https://rpc.gnosischain.com"),
    [unichain.id]:   http("https://mainnet.unichain.org"),
    [polygon.id]:    http("https://polygon-rpc.com"),
    [monad.id]:      http("https://rpc.monad.xyz"),
    [sonic.id]:      http("https://rpc.soniclabs.com"),
    [worldchain.id]: http("https://worldchain-mainnet.g.alchemy.com/public"),
    [metis.id]:      http("https://andromeda.metis.io"),
    [soneium.id]:    http("https://rpc.soneium.org"),
    [mantle.id]:     http("https://rpc.mantle.xyz"),
    [base.id]:       http("https://mainnet.base.org"),
    [plasma.id]:     http("https://rpc.plasma.to"),
    [arbitrum.id]:   http("https://arb1.arbitrum.io/rpc"),
    [celo.id]:       http("https://forno.celo.org"),
    [avalanche.id]:  http("https://api.avax.network/ext/bc/C/rpc"),
    [ink.id]:        http("https://ink.drpc.org"),
    [linea.id]:      http("https://rpc.linea.build"),
    [berachain.id]:  http("https://rpc.berachain.com"),
    [blast.id]:      http("https://rpc.blast.io"),
    [scroll.id]:     http("https://rpc.scroll.io"),
    [hyperEvm.id]:   http("https://rpc.hyperliquid.xyz/evm"),
    [megaeth.id]:    http("https://mainnet.megaeth.com/rpc"),
  },
});
